#include "L1Trigger/L1THGCal/interface/HGCalAlgoWrapperBase.h"

EDM_REGISTER_PLUGINFACTORY(HGCalHistoClusteringWrapperBaseFactory, "HGCalHistoClusteringWrapperBaseFactory");

EDM_REGISTER_PLUGINFACTORY(HGCalTowerMapsWrapperBaseFactory, "HGCalTowerMapsWrapperBaseFactory");

EDM_REGISTER_PLUGINFACTORY(HGCalStage2FilteringWrapperBaseFactory, "HGCalStage2FilteringWrapperBaseFactory");

EDM_REGISTER_PLUGINFACTORY(HGCalLayer1TruncationWrapperBaseFactory, "HGCalLayer1TruncationWrapperBaseFactory");

EDM_REGISTER_PLUGINFACTORY(HGCalLayer1PhiOrderWrapperBaseFactory, "HGCalLayer1PhiOrderWrapperBaseFactory");
