import FWCore.ParameterSet.Config as cms 

from Configuration.ProcessModifiers.enableSonicTriton_cff import enableSonicTriton
from Configuration.Eras.Era_Phase2C17I13M9_cff import Phase2C17I13M9
process = cms.Process('DIGI',Phase2C17I13M9, enableSonicTriton)

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.EventContent.EventContent_cff')
process.load('SimGeneral.MixingModule.mixNoPU_cfi')
process.load('Configuration.Geometry.GeometryExtended2026D88Reco_cff')
process.load('Configuration.Geometry.GeometryExtended2026D88_cff')
process.load('Configuration.StandardSequences.MagneticField_cff')
process.load('Configuration.StandardSequences.Generator_cff')
process.load('IOMC.EventVertexGenerators.VtxSmearedHLLHC14TeV_cfi')
process.load('GeneratorInterface.Core.genFilterSummary_cff')
process.load('Configuration.StandardSequences.SimIdeal_cff')
process.load('Configuration.StandardSequences.Digi_cff')
process.load('Configuration.StandardSequences.SimL1Emulator_cff')
process.load('Configuration.StandardSequences.DigiToRaw_cff')
process.load('Configuration.StandardSequences.EndOfProcess_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')


process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(100)
)

# Input source
process.source = cms.Source("PoolSource",
    #fileNames = cms.untracked.vstring('file:/home/submit/srothman/cmsdata/ECON_datasets/DoubleElectron_FlatPt-1To100_noPU/MINIAOD/066944a3-a061-42ac-ba45-9faadb46407a.root'),
    fileNames = cms.untracked.vstring('file:/home/submit/srothman/cmsdata/ECON_datasets/DoubleElectron_FlatPt-1To100_PU200/MINIAOD/65ce4640-c197-4c07-9fa4-cb505ab72738.root'),
    inputCommands=cms.untracked.vstring(
        'keep *',
        'drop l1tTkPrimaryVertexs_L1TkPrimaryVertex__RECO',
    )
)

process.options = cms.untracked.PSet(

)

# Production Info
process.configurationMetadata = cms.untracked.PSet(
    version = cms.untracked.string('$Revision: 1.20 $'),
    annotation = cms.untracked.string('SingleElectronPt10_cfi nevts:10'),
    name = cms.untracked.string('Applications')
)

# Output definition
process.TFileService = cms.Service(
    "TFileService",
    fileName = cms.string("/data/submit/srothman/ntuple_PU200_2.root")
    )

# Other statements
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:phase2_realistic_T21', '')

# load HGCAL TPG simulation
process.load('L1Trigger.L1THGCal.hgcalTriggerPrimitives_cff')
process.load('L1Trigger.L1THGCalUtilities.HGC3DClusterSelectors_cff')
process.load('L1Trigger.L1THGCalUtilities.hgcalTriggerNtuples_cff')
from L1Trigger.L1THGCalUtilities.hgcalTriggerChains import HGCalTriggerChains
import L1Trigger.L1THGCalUtilities.vfe as vfe
import L1Trigger.L1THGCalUtilities.concentrator as concentrator
import L1Trigger.L1THGCalUtilities.clustering2d as clustering2d
import L1Trigger.L1THGCalUtilities.clustering3d as clustering3d
import L1Trigger.L1THGCalUtilities.selectors as selectors
import L1Trigger.L1THGCalUtilities.customNtuples as ntuple
process.ntuple_triggercells.FillSimEnergy=True


chains = HGCalTriggerChains()
# Register algorithms
## VFE
chains.register_vfe("Floatingpoint", vfe.CreateVfe())
## ECON
chains.register_concentrator("Supertriggercell", concentrator.CreateSuperTriggerCell())
chains.register_concentrator("Threshold0", concentrator.CreateThreshold(
  threshold_scintillator=cms.double(-1),
  threshold_silicon=cms.double(-1)
))
chains.register_concentrator("Threshold135", concentrator.CreateThreshold(
    ))
chains.register_concentrator("Bestchoice", concentrator.CreateBestChoice())
chains.register_concentrator("AutoEncoder", concentrator.CreateAutoencoder())
chains.register_concentrator("DummyAE", concentrator.CreateTritonAE(
  inputType = "ADCT",
  modelNames = ['dummy'],
  cuts = [''],
  AEProducerName = 'AEProducerDummy',
  normType='None',
))



# chains.register_concentrator("NateAECVAE", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['dt_1_250_150_both',
#                 'dt_2_250_150_both',
#                 'dt_3_250_150_both'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAE",
#   normType='None',
#   preNorm=True,
# ))
chains.register_concentrator("NateAECVAERetrain", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_1_new_loss_retrain',
                'CVAE_dt_2_new_loss_retrain',
                'CVAE_dt_3_new_loss_retrain'],
  cuts = ['type==0', 'type==1', 'type==2'],
  AEProducerName = "AEProducerNateAECVAERetrain",
  normType='None',
  preNorm=True,
))
# chains.register_concentrator("testingAE", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['test'],
#   cuts = [''],
#   AEProducerName = "AEProducerRNDTest",
#   normType='Floating',
#   preNorm=False,
# ))
# chains.register_concentrator("NateAECVAECONV", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['CVAE_conv_dt_1_new_loss',
#                 'CVAE_conv_dt_2_new_loss',
#                 'CVAE_conv_dt_3_new_loss'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAECONV",
#   normType='Floating',
#   preNorm=True,
# ))
# chains.register_concentrator("NateAECVAECONV", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['CVAE_conv_dt_2_new_loss'
#                 ],
#   cuts = [''],
#   AEProducerName = "AEProducerNateAECVAECONV",
#   normType='Floating',
#   preNorm=True,
# ))
chains.register_concentrator("NateAECVAEMIPT", concentrator.CreateTritonAE(
  inputType = "MIPT",
  modelNames = ['CVAE_dt_1_250_150_new_loss',
                'CVAE_dt_2_250_150_new_loss',
                'CVAE_dt_3_250_150_new_loss'],
  cuts = ['type==0', 'type==1', 'type==2'],
  AEProducerName = "AEProducerNateAECVAEMIPT",
  normType='Floating',
  preNorm=True,
))
chains.register_concentrator("NateAECVAEMIP", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_1_250_150_new_loss',
                'CVAE_dt_2_250_150_new_loss',
                'CVAE_dt_3_250_150_new_loss'],
  cuts = ['type==0', 'type==1', 'type==2'],
  AEProducerName = "AEProducerNateAECVAE",
  normType='Floating',
  preNorm=True,
))
chains.register_concentrator("NateAECVAECombinedRetrain", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_1_250_150_new_loss',
                'CVAE_dt_2_new_loss_retrain',
                'CVAE_dt_3_new_loss_retrain'],
  cuts = ['type==0', 'type==1', 'type==2'],
  AEProducerName = "AEProducerNateAECVAEcombinedretrain",
  normType='Floating',
  preNorm=True,
))
# chains.register_concentrator("NateAECVAEComboLoss", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['CVAE_dt_1_combo_loss',
#                 'CVAE_dt_2_combo_loss',
#                 'CVAE_dt_3_combo_loss'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAEComboLoss",
#   normType='Floating',
#   preNorm=True,
# ))
# chains.register_concentrator("NateAECVAEComboLossGreater5", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['CVAE_dt_1_combo_loss_greater_5',
#                 'CVAE_dt_2_combo_loss_greater_5',
#                 'CVAE_dt_3_combo_loss_greater_5'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAEComboLossG5",
#   normType='Floating',
#   preNorm=True,
# ))
# chains.register_concentrator("NateAECVAEComboLossGreater7", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['CVAE_dt_1_combo_loss_greater_7',
#                 'CVAE_dt_2_combo_loss_greater_7',
#                 'CVAE_dt_3_combo_loss_greater_7'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAEComboLossG7",
#   normType='Floating',
#   preNorm=True,
# ))
chains.register_concentrator("NateManyCVAE", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_norm_1_1',
                 'CVAE_dt_norm_1_3',
                 'CVAE_dt_norm_1_3',
                 'CVAE_dt_norm_1_3',
                 'CVAE_dt_norm_1_5',
                 'CVAE_dt_norm_1_5',
                 'CVAE_dt_norm_1_7',
                 'CVAE_dt_norm_1_9',
                 'CVAE_dt_norm_1_9',
                 'CVAE_dt_norm_1_9',
                 'CVAE_dt_norm_1_11',
                 'CVAE_dt_norm_1_13',
                 'CVAE_dt_norm_1_13',
                 'CVAE_dt_norm_1_13',
                 'CVAE_dt_norm_1_15',
                 'CVAE_dt_norm_1_17',
                 'CVAE_dt_norm_1_17',
                 'CVAE_dt_norm_1_17',
                 'CVAE_dt_norm_1_19',
                 'CVAE_dt_norm_1_21',
                 'CVAE_dt_norm_1_21',
                 'CVAE_dt_norm_1_21',
                 'CVAE_dt_norm_1_23',
                 'CVAE_dt_norm_1_25',
                 'CVAE_dt_norm_1_25',
                 'CVAE_dt_norm_1_25',
                 'CVAE_dt_norm_1_27',
                 'CVAE_dt_norm_1_29',
                 'CVAE_dt_norm_1_29',
                 'CVAE_dt_norm_1_30',
                 'CVAE_dt_norm_1_31',
                 'CVAE_dt_norm_1_32',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_1_33',
                 'CVAE_dt_norm_2_1',
                 'CVAE_dt_norm_2_1',
                 'CVAE_dt_norm_2_3',
                 'CVAE_dt_norm_2_5',
                 'CVAE_dt_norm_2_5',
                 'CVAE_dt_norm_2_5',
                 'CVAE_dt_norm_2_7',
                 'CVAE_dt_norm_2_9',
                 'CVAE_dt_norm_2_9',
                 'CVAE_dt_norm_2_9',
                 'CVAE_dt_norm_2_11',
                 'CVAE_dt_norm_2_13',
                 'CVAE_dt_norm_2_13',
                 'CVAE_dt_norm_2_15',
                 'CVAE_dt_norm_2_15',
                 'CVAE_dt_norm_2_15',
                 'CVAE_dt_norm_2_17',
                 'CVAE_dt_norm_2_17',
                 'CVAE_dt_norm_2_19',
                 'CVAE_dt_norm_2_21',
                 'CVAE_dt_norm_2_21',
                 'CVAE_dt_norm_2_21',
                 'CVAE_dt_norm_2_23',
                 'CVAE_dt_norm_2_23',
                 'CVAE_dt_norm_2_25',
                 'CVAE_dt_norm_2_27',
                 'CVAE_dt_norm_2_27',
                 'CVAE_dt_norm_2_27',
                 'CVAE_dt_norm_2_29',
                 'CVAE_dt_norm_2_30',
                 'CVAE_dt_norm_2_31',
                 'CVAE_dt_norm_2_32',
                 'CVAE_dt_norm_2_32',
                 'CVAE_dt_norm_2_34',
                 'CVAE_dt_norm_2_35',
                 'CVAE_dt_norm_2_36',
                 'CVAE_dt_norm_2_37',
                 'CVAE_dt_norm_2_38',
                 'CVAE_dt_norm_2_39',
                 'CVAE_dt_norm_2_40',
                 'CVAE_dt_norm_2_41',
                 'CVAE_dt_norm_2_42',
                 'CVAE_dt_norm_2_43',
                 'CVAE_dt_norm_2_44',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_2_45',
                 'CVAE_dt_norm_3_1',
                 'CVAE_dt_norm_3_3',
                 'CVAE_dt_norm_3_3',
                 'CVAE_dt_norm_3_5',
                 'CVAE_dt_norm_3_5',
                 'CVAE_dt_norm_3_5',
                 'CVAE_dt_norm_3_7',
                 'CVAE_dt_norm_3_9',
                 'CVAE_dt_norm_3_9',
                 'CVAE_dt_norm_3_9',
                 'CVAE_dt_norm_3_11',
                 'CVAE_dt_norm_3_11',
                 'CVAE_dt_norm_3_13',
                 'CVAE_dt_norm_3_15',
                 'CVAE_dt_norm_3_15',
                 'CVAE_dt_norm_3_17',
                 'CVAE_dt_norm_3_17',
                 'CVAE_dt_norm_3_17',
                 'CVAE_dt_norm_3_19',
                 'CVAE_dt_norm_3_19',
                 'CVAE_dt_norm_3_21',
                 'CVAE_dt_norm_3_23',
                 'CVAE_dt_norm_3_23',
                 'CVAE_dt_norm_3_23',
                 'CVAE_dt_norm_3_25',
                 'CVAE_dt_norm_3_25',
                 'CVAE_dt_norm_3_27',
                 'CVAE_dt_norm_3_29',
                 'CVAE_dt_norm_3_29',
                 'CVAE_dt_norm_3_30',
                 'CVAE_dt_norm_3_31',
                 'CVAE_dt_norm_3_32',
                 'CVAE_dt_norm_3_33',
                 'CVAE_dt_norm_3_34',
                 'CVAE_dt_norm_3_35',
                 'CVAE_dt_norm_3_36',
                 'CVAE_dt_norm_3_37',
                 'CVAE_dt_norm_3_38',
                 'CVAE_dt_norm_3_39',
                 'CVAE_dt_norm_3_40',
                 'CVAE_dt_norm_3_41',
                 'CVAE_dt_norm_3_42',
                 'CVAE_dt_norm_3_43',
                 'CVAE_dt_norm_3_44',
                 'CVAE_dt_norm_3_45',
                 'CVAE_dt_norm_3_46',
                 'CVAE_dt_norm_3_47',
                 'CVAE_dt_norm_3_47',
                 'CVAE_dt_norm_3_47',
                 'CVAE_dt_norm_3_47'],
  cuts = ['type == 0 && layer == 0',
         'type == 0 && layer == 1',
         'type == 0 && layer == 2',
         'type == 0 && layer == 3',
         'type == 0 && layer == 4',
         'type == 0 && layer == 5',
         'type == 0 && layer == 6',
         'type == 0 && layer == 7',
         'type == 0 && layer == 8',
         'type == 0 && layer == 9',
         'type == 0 && layer == 10',
         'type == 0 && layer == 11',
         'type == 0 && layer == 12',
         'type == 0 && layer == 13',
         'type == 0 && layer == 14',
         'type == 0 && layer == 15',
         'type == 0 && layer == 16',
         'type == 0 && layer == 17',
         'type == 0 && layer == 18',
         'type == 0 && layer == 19',
         'type == 0 && layer == 20',
         'type == 0 && layer == 21',
         'type == 0 && layer == 22',
         'type == 0 && layer == 23',
         'type == 0 && layer == 24',
         'type == 0 && layer == 25',
         'type == 0 && layer == 26',
         'type == 0 && layer == 27',
         'type == 0 && layer == 28',
         'type == 0 && layer == 29',
         'type == 0 && layer == 30',
         'type == 0 && layer == 31',
         'type == 0 && layer == 32',
         'type == 0 && layer == 33',
         'type == 0 && layer == 34',
         'type == 0 && layer == 35',
         'type == 0 && layer == 36',
         'type == 0 && layer == 37',
         'type == 0 && layer == 38',
         'type == 0 && layer == 39',
         'type == 0 && layer == 40',
         'type == 0 && layer == 41',
         'type == 0 && layer == 42',
         'type == 0 && layer == 43',
         'type == 0 && layer == 44',
         'type == 0 && layer == 45',
         'type == 0 && layer == 46',
         'type == 0 && layer == 47',
         'type == 0 && layer == 48',
         'type == 0 && layer == 49',
         'type == 1 && layer == 0',
         'type == 1 && layer == 1',
         'type == 1 && layer == 2',
         'type == 1 && layer == 3',
         'type == 1 && layer == 4',
         'type == 1 && layer == 5',
         'type == 1 && layer == 6',
         'type == 1 && layer == 7',
         'type == 1 && layer == 8',
         'type == 1 && layer == 9',
         'type == 1 && layer == 10',
         'type == 1 && layer == 11',
         'type == 1 && layer == 12',
         'type == 1 && layer == 13',
         'type == 1 && layer == 14',
         'type == 1 && layer == 15',
         'type == 1 && layer == 16',
         'type == 1 && layer == 17',
         'type == 1 && layer == 18',
         'type == 1 && layer == 19',
         'type == 1 && layer == 20',
         'type == 1 && layer == 21',
         'type == 1 && layer == 22',
         'type == 1 && layer == 23',
         'type == 1 && layer == 24',
         'type == 1 && layer == 25',
         'type == 1 && layer == 26',
         'type == 1 && layer == 27',
         'type == 1 && layer == 28',
         'type == 1 && layer == 29',
         'type == 1 && layer == 30',
         'type == 1 && layer == 31',
         'type == 1 && layer == 32',
         'type == 1 && layer == 33',
         'type == 1 && layer == 34',
         'type == 1 && layer == 35',
         'type == 1 && layer == 36',
         'type == 1 && layer == 37',
         'type == 1 && layer == 38',
         'type == 1 && layer == 39',
         'type == 1 && layer == 40',
         'type == 1 && layer == 41',
         'type == 1 && layer == 42',
         'type == 1 && layer == 43',
         'type == 1 && layer == 44',
         'type == 1 && layer == 45',
         'type == 1 && layer == 46',
         'type == 1 && layer == 47',
         'type == 1 && layer == 48',
         'type == 1 && layer == 49',
         'type == 2 && layer == 0',
         'type == 2 && layer == 1',
         'type == 2 && layer == 2',
         'type == 2 && layer == 3',
         'type == 2 && layer == 4',
         'type == 2 && layer == 5',
         'type == 2 && layer == 6',
         'type == 2 && layer == 7',
         'type == 2 && layer == 8',
         'type == 2 && layer == 9',
         'type == 2 && layer == 10',
         'type == 2 && layer == 11',
         'type == 2 && layer == 12',
         'type == 2 && layer == 13',
         'type == 2 && layer == 14',
         'type == 2 && layer == 15',
         'type == 2 && layer == 16',
         'type == 2 && layer == 17',
         'type == 2 && layer == 18',
         'type == 2 && layer == 19',
         'type == 2 && layer == 20',
         'type == 2 && layer == 21',
         'type == 2 && layer == 22',
         'type == 2 && layer == 23',
         'type == 2 && layer == 24',
         'type == 2 && layer == 25',
         'type == 2 && layer == 26',
         'type == 2 && layer == 27',
         'type == 2 && layer == 28',
         'type == 2 && layer == 29',
         'type == 2 && layer == 30',
         'type == 2 && layer == 31',
         'type == 2 && layer == 32',
         'type == 2 && layer == 33',
         'type == 2 && layer == 34',
         'type == 2 && layer == 35',
         'type == 2 && layer == 36',
         'type == 2 && layer == 37',
         'type == 2 && layer == 38',
         'type == 2 && layer == 39',
         'type == 2 && layer == 40',
         'type == 2 && layer == 41',
         'type == 2 && layer == 42',
         'type == 2 && layer == 43',
         'type == 2 && layer == 44',
         'type == 2 && layer == 45',
         'type == 2 && layer == 46',
         'type == 2 && layer == 47',
         'type == 2 && layer == 48',
         'type == 2 && layer == 49'],
  AEProducerName = "AEProducerNateMANYCVAE",
  normType='Floating',
  preNorm=True,
))
chains.register_concentrator("NateManyCVAEComboLoss", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_norm_1_1_combo_loss',
             'CVAE_dt_norm_1_3_combo_loss',
             'CVAE_dt_norm_1_3_combo_loss',
             'CVAE_dt_norm_1_3_combo_loss',
             'CVAE_dt_norm_1_5_combo_loss',
             'CVAE_dt_norm_1_5_combo_loss',
             'CVAE_dt_norm_1_7_combo_loss',
             'CVAE_dt_norm_1_9_combo_loss',
             'CVAE_dt_norm_1_9_combo_loss',
             'CVAE_dt_norm_1_9_combo_loss',
             'CVAE_dt_norm_1_11_combo_loss',
             'CVAE_dt_norm_1_13_combo_loss',
             'CVAE_dt_norm_1_13_combo_loss',
             'CVAE_dt_norm_1_13_combo_loss',
             'CVAE_dt_norm_1_15_combo_loss',
             'CVAE_dt_norm_1_17_combo_loss',
             'CVAE_dt_norm_1_17_combo_loss',
             'CVAE_dt_norm_1_17_combo_loss',
             'CVAE_dt_norm_1_19_combo_loss',
             'CVAE_dt_norm_1_21_combo_loss',
             'CVAE_dt_norm_1_21_combo_loss',
             'CVAE_dt_norm_1_21_combo_loss',
             'CVAE_dt_norm_1_23_combo_loss',
             'CVAE_dt_norm_1_25_combo_loss',
             'CVAE_dt_norm_1_25_combo_loss',
             'CVAE_dt_norm_1_25_combo_loss',
             'CVAE_dt_norm_1_27_combo_loss',
             'CVAE_dt_norm_1_29_combo_loss',
             'CVAE_dt_norm_1_29_combo_loss',
             'CVAE_dt_norm_1_30_combo_loss',
             'CVAE_dt_norm_1_31_combo_loss',
             'CVAE_dt_norm_1_32_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_1_33_combo_loss',
             'CVAE_dt_norm_2_1_combo_loss',
             'CVAE_dt_norm_2_1_combo_loss',
             'CVAE_dt_norm_2_3_combo_loss',
             'CVAE_dt_norm_2_5_combo_loss',
             'CVAE_dt_norm_2_5_combo_loss',
             'CVAE_dt_norm_2_5_combo_loss',
             'CVAE_dt_norm_2_7_combo_loss',
             'CVAE_dt_norm_2_9_combo_loss',
             'CVAE_dt_norm_2_9_combo_loss',
             'CVAE_dt_norm_2_9_combo_loss',
             'CVAE_dt_norm_2_11_combo_loss',
             'CVAE_dt_norm_2_13_combo_loss',
             'CVAE_dt_norm_2_13_combo_loss',
             'CVAE_dt_norm_2_15_combo_loss',
             'CVAE_dt_norm_2_15_combo_loss',
             'CVAE_dt_norm_2_15_combo_loss',
             'CVAE_dt_norm_2_17_combo_loss',
             'CVAE_dt_norm_2_17_combo_loss',
             'CVAE_dt_norm_2_19_combo_loss',
             'CVAE_dt_norm_2_21_combo_loss',
             'CVAE_dt_norm_2_21_combo_loss',
             'CVAE_dt_norm_2_21_combo_loss',
             'CVAE_dt_norm_2_23_combo_loss',
             'CVAE_dt_norm_2_23_combo_loss',
             'CVAE_dt_norm_2_25_combo_loss',
             'CVAE_dt_norm_2_27_combo_loss',
             'CVAE_dt_norm_2_27_combo_loss',
             'CVAE_dt_norm_2_27_combo_loss',
             'CVAE_dt_norm_2_29_combo_loss',
             'CVAE_dt_norm_2_30_combo_loss',
             'CVAE_dt_norm_2_31_combo_loss',
             'CVAE_dt_norm_2_32_combo_loss',
             'CVAE_dt_norm_2_32_combo_loss',
             'CVAE_dt_norm_2_34_combo_loss',
             'CVAE_dt_norm_2_35_combo_loss',
             'CVAE_dt_norm_2_36_combo_loss',
             'CVAE_dt_norm_2_37_combo_loss',
             'CVAE_dt_norm_2_38_combo_loss',
             'CVAE_dt_norm_2_39_combo_loss',
             'CVAE_dt_norm_2_40_combo_loss',
             'CVAE_dt_norm_2_41_combo_loss',
             'CVAE_dt_norm_2_42_combo_loss',
             'CVAE_dt_norm_2_43_combo_loss',
             'CVAE_dt_norm_2_44_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_2_45_combo_loss',
             'CVAE_dt_norm_3_1_combo_loss',
             'CVAE_dt_norm_3_3_combo_loss',
             'CVAE_dt_norm_3_3_combo_loss',
             'CVAE_dt_norm_3_5_combo_loss',
             'CVAE_dt_norm_3_5_combo_loss',
             'CVAE_dt_norm_3_5_combo_loss',
             'CVAE_dt_norm_3_7_combo_loss',
             'CVAE_dt_norm_3_9_combo_loss',
             'CVAE_dt_norm_3_9_combo_loss',
             'CVAE_dt_norm_3_9_combo_loss',
             'CVAE_dt_norm_3_11_combo_loss',
             'CVAE_dt_norm_3_11_combo_loss',
             'CVAE_dt_norm_3_13_combo_loss',
             'CVAE_dt_norm_3_15_combo_loss',
             'CVAE_dt_norm_3_15_combo_loss',
             'CVAE_dt_norm_3_17_combo_loss',
             'CVAE_dt_norm_3_17_combo_loss',
             'CVAE_dt_norm_3_17_combo_loss',
             'CVAE_dt_norm_3_19_combo_loss',
             'CVAE_dt_norm_3_19_combo_loss',
             'CVAE_dt_norm_3_21_combo_loss',
             'CVAE_dt_norm_3_23_combo_loss',
             'CVAE_dt_norm_3_23_combo_loss',
             'CVAE_dt_norm_3_23_combo_loss',
             'CVAE_dt_norm_3_25_combo_loss',
             'CVAE_dt_norm_3_25_combo_loss',
             'CVAE_dt_norm_3_27_combo_loss',
             'CVAE_dt_norm_3_29_combo_loss',
             'CVAE_dt_norm_3_29_combo_loss',
             'CVAE_dt_norm_3_30_combo_loss',
             'CVAE_dt_norm_3_31_combo_loss',
             'CVAE_dt_norm_3_32_combo_loss',
             'CVAE_dt_norm_3_33_combo_loss',
             'CVAE_dt_norm_3_34_combo_loss',
             'CVAE_dt_norm_3_35_combo_loss',
             'CVAE_dt_norm_3_36_combo_loss',
             'CVAE_dt_norm_3_37_combo_loss',
             'CVAE_dt_norm_3_38_combo_loss',
             'CVAE_dt_norm_3_39_combo_loss',
             'CVAE_dt_norm_3_40_combo_loss',
             'CVAE_dt_norm_3_41_combo_loss',
             'CVAE_dt_norm_3_42_combo_loss',
             'CVAE_dt_norm_3_43_combo_loss',
             'CVAE_dt_norm_3_44_combo_loss',
             'CVAE_dt_norm_3_45_combo_loss',
             'CVAE_dt_norm_3_46_combo_loss',
             'CVAE_dt_norm_3_47_combo_loss',
             'CVAE_dt_norm_3_47_combo_loss',
             'CVAE_dt_norm_3_47_combo_loss',
             'CVAE_dt_norm_3_47_combo_loss'],
  cuts = ['type == 0 && layer == 0',
         'type == 0 && layer == 1',
         'type == 0 && layer == 2',
         'type == 0 && layer == 3',
         'type == 0 && layer == 4',
         'type == 0 && layer == 5',
         'type == 0 && layer == 6',
         'type == 0 && layer == 7',
         'type == 0 && layer == 8',
         'type == 0 && layer == 9',
         'type == 0 && layer == 10',
         'type == 0 && layer == 11',
         'type == 0 && layer == 12',
         'type == 0 && layer == 13',
         'type == 0 && layer == 14',
         'type == 0 && layer == 15',
         'type == 0 && layer == 16',
         'type == 0 && layer == 17',
         'type == 0 && layer == 18',
         'type == 0 && layer == 19',
         'type == 0 && layer == 20',
         'type == 0 && layer == 21',
         'type == 0 && layer == 22',
         'type == 0 && layer == 23',
         'type == 0 && layer == 24',
         'type == 0 && layer == 25',
         'type == 0 && layer == 26',
         'type == 0 && layer == 27',
         'type == 0 && layer == 28',
         'type == 0 && layer == 29',
         'type == 0 && layer == 30',
         'type == 0 && layer == 31',
         'type == 0 && layer == 32',
         'type == 0 && layer == 33',
         'type == 0 && layer == 34',
         'type == 0 && layer == 35',
         'type == 0 && layer == 36',
         'type == 0 && layer == 37',
         'type == 0 && layer == 38',
         'type == 0 && layer == 39',
         'type == 0 && layer == 40',
         'type == 0 && layer == 41',
         'type == 0 && layer == 42',
         'type == 0 && layer == 43',
         'type == 0 && layer == 44',
         'type == 0 && layer == 45',
         'type == 0 && layer == 46',
         'type == 0 && layer == 47',
         'type == 0 && layer == 48',
         'type == 0 && layer == 49',
         'type == 1 && layer == 0',
         'type == 1 && layer == 1',
         'type == 1 && layer == 2',
         'type == 1 && layer == 3',
         'type == 1 && layer == 4',
         'type == 1 && layer == 5',
         'type == 1 && layer == 6',
         'type == 1 && layer == 7',
         'type == 1 && layer == 8',
         'type == 1 && layer == 9',
         'type == 1 && layer == 10',
         'type == 1 && layer == 11',
         'type == 1 && layer == 12',
         'type == 1 && layer == 13',
         'type == 1 && layer == 14',
         'type == 1 && layer == 15',
         'type == 1 && layer == 16',
         'type == 1 && layer == 17',
         'type == 1 && layer == 18',
         'type == 1 && layer == 19',
         'type == 1 && layer == 20',
         'type == 1 && layer == 21',
         'type == 1 && layer == 22',
         'type == 1 && layer == 23',
         'type == 1 && layer == 24',
         'type == 1 && layer == 25',
         'type == 1 && layer == 26',
         'type == 1 && layer == 27',
         'type == 1 && layer == 28',
         'type == 1 && layer == 29',
         'type == 1 && layer == 30',
         'type == 1 && layer == 31',
         'type == 1 && layer == 32',
         'type == 1 && layer == 33',
         'type == 1 && layer == 34',
         'type == 1 && layer == 35',
         'type == 1 && layer == 36',
         'type == 1 && layer == 37',
         'type == 1 && layer == 38',
         'type == 1 && layer == 39',
         'type == 1 && layer == 40',
         'type == 1 && layer == 41',
         'type == 1 && layer == 42',
         'type == 1 && layer == 43',
         'type == 1 && layer == 44',
         'type == 1 && layer == 45',
         'type == 1 && layer == 46',
         'type == 1 && layer == 47',
         'type == 1 && layer == 48',
         'type == 1 && layer == 49',
         'type == 2 && layer == 0',
         'type == 2 && layer == 1',
         'type == 2 && layer == 2',
         'type == 2 && layer == 3',
         'type == 2 && layer == 4',
         'type == 2 && layer == 5',
         'type == 2 && layer == 6',
         'type == 2 && layer == 7',
         'type == 2 && layer == 8',
         'type == 2 && layer == 9',
         'type == 2 && layer == 10',
         'type == 2 && layer == 11',
         'type == 2 && layer == 12',
         'type == 2 && layer == 13',
         'type == 2 && layer == 14',
         'type == 2 && layer == 15',
         'type == 2 && layer == 16',
         'type == 2 && layer == 17',
         'type == 2 && layer == 18',
         'type == 2 && layer == 19',
         'type == 2 && layer == 20',
         'type == 2 && layer == 21',
         'type == 2 && layer == 22',
         'type == 2 && layer == 23',
         'type == 2 && layer == 24',
         'type == 2 && layer == 25',
         'type == 2 && layer == 26',
         'type == 2 && layer == 27',
         'type == 2 && layer == 28',
         'type == 2 && layer == 29',
         'type == 2 && layer == 30',
         'type == 2 && layer == 31',
         'type == 2 && layer == 32',
         'type == 2 && layer == 33',
         'type == 2 && layer == 34',
         'type == 2 && layer == 35',
         'type == 2 && layer == 36',
         'type == 2 && layer == 37',
         'type == 2 && layer == 38',
         'type == 2 && layer == 39',
         'type == 2 && layer == 40',
         'type == 2 && layer == 41',
         'type == 2 && layer == 42',
         'type == 2 && layer == 43',
         'type == 2 && layer == 44',
         'type == 2 && layer == 45',
         'type == 2 && layer == 46',
         'type == 2 && layer == 47',
         'type == 2 && layer == 48',
         'type == 2 && layer == 49'],
  AEProducerName = "AEProducerNateMANYCVAEComboLoss",
  normType='Floating',
  preNorm=True,
))
chains.register_concentrator("NateManyCVAENewLoss", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_norm_1_1_new_loss',
         'CVAE_dt_norm_1_3_new_loss',
         'CVAE_dt_norm_1_3_new_loss',
         'CVAE_dt_norm_1_3_new_loss',
         'CVAE_dt_norm_1_5_new_loss',
         'CVAE_dt_norm_1_5_new_loss',
         'CVAE_dt_norm_1_7_new_loss',
         'CVAE_dt_norm_1_9_new_loss',
         'CVAE_dt_norm_1_9_new_loss',
         'CVAE_dt_norm_1_9_new_loss',
         'CVAE_dt_norm_1_11_new_loss',
         'CVAE_dt_norm_1_13_new_loss',
         'CVAE_dt_norm_1_13_new_loss',
         'CVAE_dt_norm_1_13_new_loss',
         'CVAE_dt_norm_1_15_new_loss',
         'CVAE_dt_norm_1_17_new_loss',
         'CVAE_dt_norm_1_17_new_loss',
         'CVAE_dt_norm_1_17_new_loss',
         'CVAE_dt_norm_1_19_new_loss',
         'CVAE_dt_norm_1_21_new_loss',
         'CVAE_dt_norm_1_21_new_loss',
         'CVAE_dt_norm_1_21_new_loss',
         'CVAE_dt_norm_1_23_new_loss',
         'CVAE_dt_norm_1_25_new_loss',
         'CVAE_dt_norm_1_25_new_loss',
         'CVAE_dt_norm_1_25_new_loss',
         'CVAE_dt_norm_1_27_new_loss',
         'CVAE_dt_norm_1_29_new_loss',
         'CVAE_dt_norm_1_29_new_loss',
         'CVAE_dt_norm_1_30_new_loss',
         'CVAE_dt_norm_1_31_new_loss',
         'CVAE_dt_norm_1_32_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_1_33_new_loss',
         'CVAE_dt_norm_2_1_new_loss',
         'CVAE_dt_norm_2_1_new_loss',
         'CVAE_dt_norm_2_3_new_loss',
         'CVAE_dt_norm_2_5_new_loss',
         'CVAE_dt_norm_2_5_new_loss',
         'CVAE_dt_norm_2_5_new_loss',
         'CVAE_dt_norm_2_7_new_loss',
         'CVAE_dt_norm_2_9_new_loss',
         'CVAE_dt_norm_2_9_new_loss',
         'CVAE_dt_norm_2_9_new_loss',
         'CVAE_dt_norm_2_11_new_loss',
         'CVAE_dt_norm_2_13_new_loss',
         'CVAE_dt_norm_2_13_new_loss',
         'CVAE_dt_norm_2_15_new_loss',
         'CVAE_dt_norm_2_15_new_loss',
         'CVAE_dt_norm_2_15_new_loss',
         'CVAE_dt_norm_2_17_new_loss',
         'CVAE_dt_norm_2_17_new_loss',
         'CVAE_dt_norm_2_19_new_loss',
         'CVAE_dt_norm_2_21_new_loss',
         'CVAE_dt_norm_2_21_new_loss',
         'CVAE_dt_norm_2_21_new_loss',
         'CVAE_dt_norm_2_23_new_loss',
         'CVAE_dt_norm_2_23_new_loss',
         'CVAE_dt_norm_2_25_new_loss',
         'CVAE_dt_norm_2_27_new_loss',
         'CVAE_dt_norm_2_27_new_loss',
         'CVAE_dt_norm_2_27_new_loss',
         'CVAE_dt_norm_2_29_new_loss',
         'CVAE_dt_norm_2_30_new_loss',
         'CVAE_dt_norm_2_31_new_loss',
         'CVAE_dt_norm_2_32_new_loss',
         'CVAE_dt_norm_2_32_new_loss',
         'CVAE_dt_norm_2_34_new_loss',
         'CVAE_dt_norm_2_35_new_loss',
         'CVAE_dt_norm_2_36_new_loss',
         'CVAE_dt_norm_2_37_new_loss',
         'CVAE_dt_norm_2_38_new_loss',
         'CVAE_dt_norm_2_39_new_loss',
         'CVAE_dt_norm_2_40_new_loss',
         'CVAE_dt_norm_2_41_new_loss',
         'CVAE_dt_norm_2_42_new_loss',
         'CVAE_dt_norm_2_43_new_loss',
         'CVAE_dt_norm_2_44_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_2_45_new_loss',
         'CVAE_dt_norm_3_1_new_loss',
         'CVAE_dt_norm_3_3_new_loss',
         'CVAE_dt_norm_3_3_new_loss',
         'CVAE_dt_norm_3_5_new_loss',
         'CVAE_dt_norm_3_5_new_loss',
         'CVAE_dt_norm_3_5_new_loss',
         'CVAE_dt_norm_3_7_new_loss',
         'CVAE_dt_norm_3_9_new_loss',
         'CVAE_dt_norm_3_9_new_loss',
         'CVAE_dt_norm_3_9_new_loss',
         'CVAE_dt_norm_3_11_new_loss',
         'CVAE_dt_norm_3_11_new_loss',
         'CVAE_dt_norm_3_13_new_loss',
         'CVAE_dt_norm_3_15_new_loss',
         'CVAE_dt_norm_3_15_new_loss',
         'CVAE_dt_norm_3_17_new_loss',
         'CVAE_dt_norm_3_17_new_loss',
         'CVAE_dt_norm_3_17_new_loss',
         'CVAE_dt_norm_3_19_new_loss',
         'CVAE_dt_norm_3_19_new_loss',
         'CVAE_dt_norm_3_21_new_loss',
         'CVAE_dt_norm_3_23_new_loss',
         'CVAE_dt_norm_3_23_new_loss',
         'CVAE_dt_norm_3_23_new_loss',
         'CVAE_dt_norm_3_25_new_loss',
         'CVAE_dt_norm_3_25_new_loss',
         'CVAE_dt_norm_3_27_new_loss',
         'CVAE_dt_norm_3_29_new_loss',
         'CVAE_dt_norm_3_29_new_loss',
         'CVAE_dt_norm_3_30_new_loss',
         'CVAE_dt_norm_3_31_new_loss',
         'CVAE_dt_norm_3_32_new_loss',
         'CVAE_dt_norm_3_33_new_loss',
         'CVAE_dt_norm_3_34_new_loss',
         'CVAE_dt_norm_3_35_new_loss',
         'CVAE_dt_norm_3_36_new_loss',
         'CVAE_dt_norm_3_37_new_loss',
         'CVAE_dt_norm_3_38_new_loss',
         'CVAE_dt_norm_3_39_new_loss',
         'CVAE_dt_norm_3_40_new_loss',
         'CVAE_dt_norm_3_41_new_loss',
         'CVAE_dt_norm_3_42_new_loss',
         'CVAE_dt_norm_3_43_new_loss',
         'CVAE_dt_norm_3_44_new_loss',
         'CVAE_dt_norm_3_45_new_loss',
         'CVAE_dt_norm_3_46_new_loss',
         'CVAE_dt_norm_3_47_new_loss',
         'CVAE_dt_norm_3_47_new_loss',
         'CVAE_dt_norm_3_47_new_loss',
         'CVAE_dt_norm_3_47_new_loss'],
  cuts = ['type == 0 && layer == 0',
         'type == 0 && layer == 1',
         'type == 0 && layer == 2',
         'type == 0 && layer == 3',
         'type == 0 && layer == 4',
         'type == 0 && layer == 5',
         'type == 0 && layer == 6',
         'type == 0 && layer == 7',
         'type == 0 && layer == 8',
         'type == 0 && layer == 9',
         'type == 0 && layer == 10',
         'type == 0 && layer == 11',
         'type == 0 && layer == 12',
         'type == 0 && layer == 13',
         'type == 0 && layer == 14',
         'type == 0 && layer == 15',
         'type == 0 && layer == 16',
         'type == 0 && layer == 17',
         'type == 0 && layer == 18',
         'type == 0 && layer == 19',
         'type == 0 && layer == 20',
         'type == 0 && layer == 21',
         'type == 0 && layer == 22',
         'type == 0 && layer == 23',
         'type == 0 && layer == 24',
         'type == 0 && layer == 25',
         'type == 0 && layer == 26',
         'type == 0 && layer == 27',
         'type == 0 && layer == 28',
         'type == 0 && layer == 29',
         'type == 0 && layer == 30',
         'type == 0 && layer == 31',
         'type == 0 && layer == 32',
         'type == 0 && layer == 33',
         'type == 0 && layer == 34',
         'type == 0 && layer == 35',
         'type == 0 && layer == 36',
         'type == 0 && layer == 37',
         'type == 0 && layer == 38',
         'type == 0 && layer == 39',
         'type == 0 && layer == 40',
         'type == 0 && layer == 41',
         'type == 0 && layer == 42',
         'type == 0 && layer == 43',
         'type == 0 && layer == 44',
         'type == 0 && layer == 45',
         'type == 0 && layer == 46',
         'type == 0 && layer == 47',
         'type == 0 && layer == 48',
         'type == 0 && layer == 49',
         'type == 1 && layer == 0',
         'type == 1 && layer == 1',
         'type == 1 && layer == 2',
         'type == 1 && layer == 3',
         'type == 1 && layer == 4',
         'type == 1 && layer == 5',
         'type == 1 && layer == 6',
         'type == 1 && layer == 7',
         'type == 1 && layer == 8',
         'type == 1 && layer == 9',
         'type == 1 && layer == 10',
         'type == 1 && layer == 11',
         'type == 1 && layer == 12',
         'type == 1 && layer == 13',
         'type == 1 && layer == 14',
         'type == 1 && layer == 15',
         'type == 1 && layer == 16',
         'type == 1 && layer == 17',
         'type == 1 && layer == 18',
         'type == 1 && layer == 19',
         'type == 1 && layer == 20',
         'type == 1 && layer == 21',
         'type == 1 && layer == 22',
         'type == 1 && layer == 23',
         'type == 1 && layer == 24',
         'type == 1 && layer == 25',
         'type == 1 && layer == 26',
         'type == 1 && layer == 27',
         'type == 1 && layer == 28',
         'type == 1 && layer == 29',
         'type == 1 && layer == 30',
         'type == 1 && layer == 31',
         'type == 1 && layer == 32',
         'type == 1 && layer == 33',
         'type == 1 && layer == 34',
         'type == 1 && layer == 35',
         'type == 1 && layer == 36',
         'type == 1 && layer == 37',
         'type == 1 && layer == 38',
         'type == 1 && layer == 39',
         'type == 1 && layer == 40',
         'type == 1 && layer == 41',
         'type == 1 && layer == 42',
         'type == 1 && layer == 43',
         'type == 1 && layer == 44',
         'type == 1 && layer == 45',
         'type == 1 && layer == 46',
         'type == 1 && layer == 47',
         'type == 1 && layer == 48',
         'type == 1 && layer == 49',
         'type == 2 && layer == 0',
         'type == 2 && layer == 1',
         'type == 2 && layer == 2',
         'type == 2 && layer == 3',
         'type == 2 && layer == 4',
         'type == 2 && layer == 5',
         'type == 2 && layer == 6',
         'type == 2 && layer == 7',
         'type == 2 && layer == 8',
         'type == 2 && layer == 9',
         'type == 2 && layer == 10',
         'type == 2 && layer == 11',
         'type == 2 && layer == 12',
         'type == 2 && layer == 13',
         'type == 2 && layer == 14',
         'type == 2 && layer == 15',
         'type == 2 && layer == 16',
         'type == 2 && layer == 17',
         'type == 2 && layer == 18',
         'type == 2 && layer == 19',
         'type == 2 && layer == 20',
         'type == 2 && layer == 21',
         'type == 2 && layer == 22',
         'type == 2 && layer == 23',
         'type == 2 && layer == 24',
         'type == 2 && layer == 25',
         'type == 2 && layer == 26',
         'type == 2 && layer == 27',
         'type == 2 && layer == 28',
         'type == 2 && layer == 29',
         'type == 2 && layer == 30',
         'type == 2 && layer == 31',
         'type == 2 && layer == 32',
         'type == 2 && layer == 33',
         'type == 2 && layer == 34',
         'type == 2 && layer == 35',
         'type == 2 && layer == 36',
         'type == 2 && layer == 37',
         'type == 2 && layer == 38',
         'type == 2 && layer == 39',
         'type == 2 && layer == 40',
         'type == 2 && layer == 41',
         'type == 2 && layer == 42',
         'type == 2 && layer == 43',
         'type == 2 && layer == 44',
         'type == 2 && layer == 45',
         'type == 2 && layer == 46',
         'type == 2 && layer == 47',
         'type == 2 && layer == 48',
         'type == 2 && layer == 49'],
  AEProducerName = "AEProducerNateMANYCVAENewloss",
  normType='Floating',
  preNorm=True,
))
chains.register_concentrator("NateManyCVAERetrain", concentrator.CreateTritonAE(
  inputType = "MIP",
  modelNames = ['CVAE_dt_norm_1_1_retry',
             'CVAE_dt_norm_1_3_retry',
             'CVAE_dt_norm_1_3_retry',
             'CVAE_dt_norm_1_3_retry',
             'CVAE_dt_norm_1_5_retry',
             'CVAE_dt_norm_1_5_retry',
             'CVAE_dt_norm_1_7_retry',
             'CVAE_dt_norm_1_9_retry',
             'CVAE_dt_norm_1_9_retry',
             'CVAE_dt_norm_1_9_retry',
             'CVAE_dt_norm_1_11_retry',
             'CVAE_dt_norm_1_13_retry',
             'CVAE_dt_norm_1_13_retry',
             'CVAE_dt_norm_1_13_retry',
             'CVAE_dt_norm_1_15_retry',
             'CVAE_dt_norm_1_17_retry',
             'CVAE_dt_norm_1_17_retry',
             'CVAE_dt_norm_1_17_retry',
             'CVAE_dt_norm_1_19_retry',
             'CVAE_dt_norm_1_21_retry',
             'CVAE_dt_norm_1_21_retry',
             'CVAE_dt_norm_1_21_retry',
             'CVAE_dt_norm_1_23_retry',
             'CVAE_dt_norm_1_25_retry',
             'CVAE_dt_norm_1_25_retry',
             'CVAE_dt_norm_1_25_retry',
             'CVAE_dt_norm_1_27_retry',
             'CVAE_dt_norm_1_29_retry',
             'CVAE_dt_norm_1_29_retry',
             'CVAE_dt_norm_1_30_retry',
             'CVAE_dt_norm_1_31_retry',
             'CVAE_dt_norm_1_32_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_1_33_retry',
             'CVAE_dt_norm_2_1_retry',
             'CVAE_dt_norm_2_1_retry',
             'CVAE_dt_norm_2_3_retry',
             'CVAE_dt_norm_2_5_retry',
             'CVAE_dt_norm_2_5_retry',
             'CVAE_dt_norm_2_5_retry',
             'CVAE_dt_norm_2_7_retry',
             'CVAE_dt_norm_2_9_retry',
             'CVAE_dt_norm_2_9_retry',
             'CVAE_dt_norm_2_9_retry',
             'CVAE_dt_norm_2_11_retry',
             'CVAE_dt_norm_2_13_retry',
             'CVAE_dt_norm_2_13_retry',
             'CVAE_dt_norm_2_15_retry',
             'CVAE_dt_norm_2_15_retry',
             'CVAE_dt_norm_2_15_retry',
             'CVAE_dt_norm_2_17_retry',
             'CVAE_dt_norm_2_17_retry',
             'CVAE_dt_norm_2_19_retry',
             'CVAE_dt_norm_2_21_retry',
             'CVAE_dt_norm_2_21_retry',
             'CVAE_dt_norm_2_21_retry',
             'CVAE_dt_norm_2_23_retry',
             'CVAE_dt_norm_2_23_retry',
             'CVAE_dt_norm_2_25_retry',
             'CVAE_dt_norm_2_27_retry',
             'CVAE_dt_norm_2_27_retry',
             'CVAE_dt_norm_2_27_retry',
             'CVAE_dt_norm_2_29_retry',
             'CVAE_dt_norm_2_30_retry',
             'CVAE_dt_norm_2_31_retry',
             'CVAE_dt_norm_2_32_retry',
             'CVAE_dt_norm_2_32_retry',
             'CVAE_dt_norm_2_34_retry',
             'CVAE_dt_norm_2_35_retry',
             'CVAE_dt_norm_2_36_retry',
             'CVAE_dt_norm_2_37_retry',
             'CVAE_dt_norm_2_38_retry',
             'CVAE_dt_norm_2_39_retry',
             'CVAE_dt_norm_2_40_retry',
             'CVAE_dt_norm_2_41_retry',
             'CVAE_dt_norm_2_42_retry',
             'CVAE_dt_norm_2_43_retry',
             'CVAE_dt_norm_2_44_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_2_45_retry',
             'CVAE_dt_norm_3_1_retry',
             'CVAE_dt_norm_3_3_retry',
             'CVAE_dt_norm_3_3_retry',
             'CVAE_dt_norm_3_5_retry',
             'CVAE_dt_norm_3_5_retry',
             'CVAE_dt_norm_3_5_retry',
             'CVAE_dt_norm_3_7_retry',
             'CVAE_dt_norm_3_9_retry',
             'CVAE_dt_norm_3_9_retry',
             'CVAE_dt_norm_3_9_retry',
             'CVAE_dt_norm_3_11_retry',
             'CVAE_dt_norm_3_11_retry',
             'CVAE_dt_norm_3_13_retry',
             'CVAE_dt_norm_3_15_retry',
             'CVAE_dt_norm_3_15_retry',
             'CVAE_dt_norm_3_17_retry',
             'CVAE_dt_norm_3_17_retry',
             'CVAE_dt_norm_3_17_retry',
             'CVAE_dt_norm_3_19_retry',
             'CVAE_dt_norm_3_19_retry',
             'CVAE_dt_norm_3_21_retry',
             'CVAE_dt_norm_3_23_retry',
             'CVAE_dt_norm_3_23_retry',
             'CVAE_dt_norm_3_23_retry',
             'CVAE_dt_norm_3_25_retry',
             'CVAE_dt_norm_3_25_retry',
             'CVAE_dt_norm_3_27_retry',
             'CVAE_dt_norm_3_29_retry',
             'CVAE_dt_norm_3_29_retry',
             'CVAE_dt_norm_3_30_retry',
             'CVAE_dt_norm_3_31_retry',
             'CVAE_dt_norm_3_32_retry',
             'CVAE_dt_norm_3_33_retry',
             'CVAE_dt_norm_3_34_retry',
             'CVAE_dt_norm_3_35_retry',
             'CVAE_dt_norm_3_36_retry',
             'CVAE_dt_norm_3_37_retry',
             'CVAE_dt_norm_3_38_retry',
             'CVAE_dt_norm_3_39_retry',
             'CVAE_dt_norm_3_40_retry',
             'CVAE_dt_norm_3_41_retry',
             'CVAE_dt_norm_3_42_retry',
             'CVAE_dt_norm_3_43_retry',
             'CVAE_dt_norm_3_44_retry',
             'CVAE_dt_norm_3_45_retry',
             'CVAE_dt_norm_3_46_retry',
             'CVAE_dt_norm_3_47_retry',
             'CVAE_dt_norm_3_47_retry',
             'CVAE_dt_norm_3_47_retry',
             'CVAE_dt_norm_3_47_retry'],
  cuts = ['type == 0 && layer == 0',
         'type == 0 && layer == 1',
         'type == 0 && layer == 2',
         'type == 0 && layer == 3',
         'type == 0 && layer == 4',
         'type == 0 && layer == 5',
         'type == 0 && layer == 6',
         'type == 0 && layer == 7',
         'type == 0 && layer == 8',
         'type == 0 && layer == 9',
         'type == 0 && layer == 10',
         'type == 0 && layer == 11',
         'type == 0 && layer == 12',
         'type == 0 && layer == 13',
         'type == 0 && layer == 14',
         'type == 0 && layer == 15',
         'type == 0 && layer == 16',
         'type == 0 && layer == 17',
         'type == 0 && layer == 18',
         'type == 0 && layer == 19',
         'type == 0 && layer == 20',
         'type == 0 && layer == 21',
         'type == 0 && layer == 22',
         'type == 0 && layer == 23',
         'type == 0 && layer == 24',
         'type == 0 && layer == 25',
         'type == 0 && layer == 26',
         'type == 0 && layer == 27',
         'type == 0 && layer == 28',
         'type == 0 && layer == 29',
         'type == 0 && layer == 30',
         'type == 0 && layer == 31',
         'type == 0 && layer == 32',
         'type == 0 && layer == 33',
         'type == 0 && layer == 34',
         'type == 0 && layer == 35',
         'type == 0 && layer == 36',
         'type == 0 && layer == 37',
         'type == 0 && layer == 38',
         'type == 0 && layer == 39',
         'type == 0 && layer == 40',
         'type == 0 && layer == 41',
         'type == 0 && layer == 42',
         'type == 0 && layer == 43',
         'type == 0 && layer == 44',
         'type == 0 && layer == 45',
         'type == 0 && layer == 46',
         'type == 0 && layer == 47',
         'type == 0 && layer == 48',
         'type == 0 && layer == 49',
         'type == 1 && layer == 0',
         'type == 1 && layer == 1',
         'type == 1 && layer == 2',
         'type == 1 && layer == 3',
         'type == 1 && layer == 4',
         'type == 1 && layer == 5',
         'type == 1 && layer == 6',
         'type == 1 && layer == 7',
         'type == 1 && layer == 8',
         'type == 1 && layer == 9',
         'type == 1 && layer == 10',
         'type == 1 && layer == 11',
         'type == 1 && layer == 12',
         'type == 1 && layer == 13',
         'type == 1 && layer == 14',
         'type == 1 && layer == 15',
         'type == 1 && layer == 16',
         'type == 1 && layer == 17',
         'type == 1 && layer == 18',
         'type == 1 && layer == 19',
         'type == 1 && layer == 20',
         'type == 1 && layer == 21',
         'type == 1 && layer == 22',
         'type == 1 && layer == 23',
         'type == 1 && layer == 24',
         'type == 1 && layer == 25',
         'type == 1 && layer == 26',
         'type == 1 && layer == 27',
         'type == 1 && layer == 28',
         'type == 1 && layer == 29',
         'type == 1 && layer == 30',
         'type == 1 && layer == 31',
         'type == 1 && layer == 32',
         'type == 1 && layer == 33',
         'type == 1 && layer == 34',
         'type == 1 && layer == 35',
         'type == 1 && layer == 36',
         'type == 1 && layer == 37',
         'type == 1 && layer == 38',
         'type == 1 && layer == 39',
         'type == 1 && layer == 40',
         'type == 1 && layer == 41',
         'type == 1 && layer == 42',
         'type == 1 && layer == 43',
         'type == 1 && layer == 44',
         'type == 1 && layer == 45',
         'type == 1 && layer == 46',
         'type == 1 && layer == 47',
         'type == 1 && layer == 48',
         'type == 1 && layer == 49',
         'type == 2 && layer == 0',
         'type == 2 && layer == 1',
         'type == 2 && layer == 2',
         'type == 2 && layer == 3',
         'type == 2 && layer == 4',
         'type == 2 && layer == 5',
         'type == 2 && layer == 6',
         'type == 2 && layer == 7',
         'type == 2 && layer == 8',
         'type == 2 && layer == 9',
         'type == 2 && layer == 10',
         'type == 2 && layer == 11',
         'type == 2 && layer == 12',
         'type == 2 && layer == 13',
         'type == 2 && layer == 14',
         'type == 2 && layer == 15',
         'type == 2 && layer == 16',
         'type == 2 && layer == 17',
         'type == 2 && layer == 18',
         'type == 2 && layer == 19',
         'type == 2 && layer == 20',
         'type == 2 && layer == 21',
         'type == 2 && layer == 22',
         'type == 2 && layer == 23',
         'type == 2 && layer == 24',
         'type == 2 && layer == 25',
         'type == 2 && layer == 26',
         'type == 2 && layer == 27',
         'type == 2 && layer == 28',
         'type == 2 && layer == 29',
         'type == 2 && layer == 30',
         'type == 2 && layer == 31',
         'type == 2 && layer == 32',
         'type == 2 && layer == 33',
         'type == 2 && layer == 34',
         'type == 2 && layer == 35',
         'type == 2 && layer == 36',
         'type == 2 && layer == 37',
         'type == 2 && layer == 38',
         'type == 2 && layer == 39',
         'type == 2 && layer == 40',
         'type == 2 && layer == 41',
         'type == 2 && layer == 42',
         'type == 2 && layer == 43',
         'type == 2 && layer == 44',
         'type == 2 && layer == 45',
         'type == 2 && layer == 46',
         'type == 2 && layer == 47',
         'type == 2 && layer == 48',
         'type == 2 && layer == 49'],
  AEProducerName = "AEProducerNateMANYCVAERetrain",
  normType='Floating',
  preNorm=True,
))
# chains.register_concentrator("NateAECVAEConv", concentrator.CreateTritonAE(
#   inputType = "MIP",
#   modelNames = ['dt_1_both_new_loss_update',
#                 'dt_2_both_new_loss_update',
#                 'dt_3_both_new_loss_update'],
#   cuts = ['type==0', 'type==1', 'type==2'],
#   AEProducerName = "AEProducerNateAECVAEconv",
#   normType='Floating',
#   preNorm=True,
# ))
chains.register_concentrator("RohanAE", concentrator.CreateAutoencoder(
 threshold_scintillator=-1,
 threshold_silicon=-1,
 zeroSuppresionThreshold=-1,
 saveEncodedValues=True,
 preserveModuleSum=True
))
#chains.register_concentrator("RohanAEFP", concentrator.CreateAutoencoder(
#  threshold_scintillator=-1,
#  threshold_silicon=-1,
#  zeroSuppresionThreshold=-1,
#  saveEncodedValues=True,
#  preserveModuleSum=True,
#  nBitsPerInput=-1,
#  maxBitsPerOutput=-1,
#  clipTransverseADC=False,
#))

## BE1
chains.register_backend1("Dummy", clustering2d.CreateDummy())
#chains.register_backend1("Distance", clustering2d.CreateDistance())
#chains.register_backend1("Topological", clustering2d.CreateTopological())
#chains.register_backend1("ConstrTopological", clustering2d.CreateConstrTopological())
## BE2
chains.register_backend2("Histomax", clustering3d.CreateHistoMax())
#chains.register_backend2("Distance", clustering3d.CreateDistance())
#chains.register_backend2("Dbscan", clustering3d.CreateDbscan())
# Register selector
chains.register_selector("Dummy", selectors.CreateDummy())


# Register ntuples
ntuple_list = ['event', 'gen', 'multiclusters', 'triggercells', 'econdata']
chains.register_ntuple("nTuple", ntuple.CreateNtuple(ntuple_list))

# Register trigger chains


# concentrator_algos = ['Threshold0', "NateAECVAE","NateAECVAEconv"]
concentrator_algos = ['Threshold0','Threshold135', "RohanAE", "NateAECVAERetrain"]#'NateAECVAERetrain','RohanAE','NateManyCVAEComboLoss','NateManyCVAERetrain','NateManyCVAENewLoss']

# concentrator_algos = ['Threshold0',"NateAECVAE",'RohanAE','Threshold135','NateManyCVAENewLoss','NateManyCVAERetrain','NateManyCVAEComboLoss']#,'NateAECVAERetrain'

backend1_algos = ['Dummy']# 'Distance'] #'Topological']#, 'ConstrTopological']
backend2_algos = ['Histomax']#, 'Distance', 'Dbscan']
## Make cross product fo ECON and BE algos
import itertools
for cc,be1,be2 in itertools.product(concentrator_algos,backend1_algos, backend2_algos):
    chains.register_chain('Floatingpoint', cc, be1, be2, 'Dummy', 'nTuple')

process = chains.create_sequences(process)

# Remove towers from sequence
process.L1THGCalTriggerPrimitives.remove(process.L1THGCalTowerMap)
process.L1THGCalTriggerPrimitives.remove(process.L1THGCalTower)

process.hgcl1tpg_step = cms.Path(process.L1THGCalTriggerPrimitives)
process.selector_step = cms.Path(process.L1THGCalTriggerSelector)
process.ntuple_step = cms.Path(process.L1THGCalTriggerNtuples)

# Schedule definition
process.schedule = cms.Schedule(process.hgcl1tpg_step, process.selector_step, process.ntuple_step)

# Add early deletion of temporary data products to reduce peak memory need
from Configuration.StandardSequences.earlyDeleteSettings_cff import customiseEarlyDelete
process = customiseEarlyDelete(process)
# End adding early deletion

